image: mcr.microsoft.com/dotnet/core/sdk:latest

stages:
    - build

build:
    stage: build
    script:
        - "dotnet build src\\JamSoft.AvaloniaUI.Dialogs.sln"
    artifacts:
      paths:
        - bin/